name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
      - name: Setup Java JDK
  uses: actions/setup-java@v2.1.0
  with:
    # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
    java-version: 
    # Java distribution. See the list of supported distributions in README file
    distribution: 
    # The package type (jdk, jre, jdk+fx, jre+fx)
    java-package: # optional, default is jdk
    # The architecture of the package
    architecture: # optional, default is x64
    # Path to where the compressed JDK is located
    jdkFile: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec
    check-latest: # optional
    # ID of the distributionManagement repository in the pom.xml file. Default is `github`
    server-id: # optional, default is github
    # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
    server-username: # optional, default is GITHUB_ACTOR
    # Environment variable name for password or token for authentication to the Apache Maven repository. Default is $GITHUB_TOKEN
    server-password: # optional, default is GITHUB_TOKEN
    # Path to where the settings.xml file will be written. Default is ~/.m2.
    settings-path: # optional
    # Overwrite the settings.xml file if it exists. Default is "true".
    overwrite-settings: # optional, default is true
    # GPG private key to import. Default is empty string.
    gpg-private-key: # optional
    # Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.
    gpg-passphrase: # optional
      
      - name: Leiningen Dependency Update Action
  # You may pin to the exact commit or the version.
  # uses: nnichols/leiningen-dependency-update-action@3e4070fab07fa37e67015cb811f937559e85a4f9
  uses: nnichols/leiningen-dependency-update-action@v1
  with:
    # A GitHub auth token to be able to create the pull request
    github-token: 
    # the branch to commit to
    branch: # default is master
    # The email address used to create the version commit with.
    git-email: # default is 41898282+github-actions[bot]@users.noreply.github.com
    # The name to use for the version commit. e.g. github.actor
    git-username: # default is github-actions[bot]
    # Artifact names to exclude (space separated).
    excludes: # default is 
    # Search paths for projects (space separated).
    directories: # default is 
    # Project types to skip to search (space separated). Must be one of `boot`, `clojure-cli`, `github-action`, `pom`, `shadow-cljs` and `leiningen`.
    skips: # default is 
    # Updates all outdated dependencies in a single pull request. Set to "true" to enable
    batch: # default is false
